### ISSUE TITLE
添加 Google 分析

### ISSUE THREAD

**Issue by fdjkgh580** [fdjkgh580/issue_kypost#14]
雅德客、光洋都要

**Comment by dream3cmp3** [comment]
1.      插入網站分析工具

請將其複製並貼入每個所要追蹤網頁的程式碼。

 
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
 
  ga('create', 'UA-58074609-1', 'auto');
  ga('send', 'pageview');
 
</script>
