### ISSUE TITLE
0106修正

### ISSUE THREAD

**Issue by Wondershow-Mars** [fdjkgh580/issue_kypost#20]
2015/1/5-renew
待改
1.	首頁下方橫式條目，第一欄英文為Profile
 
![image](https://cloud.githubusercontent.com/assets/10335170/5623117/f551472c-9588-11e4-9d1c-9eec7f89cfe4.png)

2.	點入內頁，過長英文標題顯示不完整
 
![image](https://cloud.githubusercontent.com/assets/10335170/5623120/f948ede4-9588-11e4-87e8-6772e0dafc61.png)

3.	日期可否於後台自行填入，而非預設為上架日期？因為目前訊息或作品都是於短時間內一次上架，若顯示最近日期，邏輯會有些奇怪（本項非必要更改）
![image](https://cloud.githubusercontent.com/assets/10335170/5623121/003800d6-9589-11e4-83a0-122f705f7989.png)
 

4.	簡體模式的「作品集」頁，國外展場空間設計　頁標題仍為繁體
![image](https://cloud.githubusercontent.com/assets/10335170/5623126/08f38b8c-9589-11e4-9e45-6ba2d7a85ef7.png)
 

5.	簡體模式下，以下頁面短TITLE依然為繁體字（如下圖）
![image](https://cloud.githubusercontent.com/assets/10335170/5623130/0e6ce496-9589-11e4-8a6c-75e082cd8ca3.png)

**Comment by fdjkgh580** [comment]
@Wondershow-Mars  
點入內頁，過長英文標題顯示不完整 -> 這樣下方的空白他們還有還有副標題耶

**Comment by fdjkgh580** [comment]
@Wondershow-Mars 
簡體模式下，以下頁面短TITLE依然為繁體字（如下圖）->
目前看是簡體喔~
