### ISSUE TITLE
網頁內的next和preview

### ISSUE THREAD

**Issue by Wondershow-Mars** [fdjkgh580/issue_kypost#23]
是否因為電腦螢幕的大小，造成一半壓在說明文上?
寬版螢幕是正常的，但是窄版的螢幕好像會造成下面的問題
![image](https://cloud.githubusercontent.com/assets/10335170/5774146/cd1d34da-9da5-11e4-9016-6c6f3dc73388.png)

**Comment by fdjkgh580** [comment]
@Wondershow-Mars 這樣1280的螢幕不會喔

![image](https://cloud.githubusercontent.com/assets/4414580/5811570/da7822ca-a093-11e4-9861-145145e8c4a4.png)
