### ISSUE TITLE
KY網站-連絡我們(內容翻譯協助)

### ISSUE THREAD

**Issue by Wondershow-Mars** [fdjkgh580/issue_kypost#24]
[簡體版]
公司名称           连络电话
姓        名           联络信箱
 
询问主题
商业空间设计    活动空间设计    展览空间设计    环境空间设计    其他服务
 
 
主旨
询问内容
 
谢谢您的留言，我们将尽快派专人与您连络。
 
确认送出

-------------------------------------------------------------------------------------------
.

[英文版]
Company name                      Telephone
Name                                     E-mail
 
Theme
Commercial interior design
Activity planning
Exhibition design
Space design
Other services
 
 
Subject
Question
 
Thank you for your message, we’ll contact you soon!
 
submit

**Comment by fdjkgh580** [comment]
@Dog0412 
這邊圖片要翻譯的
![image](https://cloud.githubusercontent.com/assets/4414580/5798208/5bc1bc36-a000-11e4-92de-249732692c87.png)

按鈕的也是
![image](https://cloud.githubusercontent.com/assets/4414580/5798218/6fe4101a-a000-11e4-8d7d-e6f25129c6e0.png)

**Comment by Dog0412** [comment]
已加入簡體與英文圖片
![-1](https://cloud.githubusercontent.com/assets/10335557/5811430/e33f093e-a091-11e4-9620-a49bf17970e2.jpg)
