### ISSUE TITLE
信件測試問題

### ISSUE THREAD

**Issue by dream3cmp3** [fdjkgh580/issue_kypost#27]
2.      請協助測試網站設計－聯絡我們　

「每個聯絡人是否皆可收到客戶詢問」

因為昨天測試過，只有第一個人會收到訊息。

![image](https://cloud.githubusercontent.com/assets/10286429/5813622/56eeb676-a0bb-11e4-87b1-471f5fb2afad.png)

**Comment by fdjkgh580** [comment]
@dream3cmp3  
已完成這部份的修改與測試，請他們有空再測試一下
