### ISSUE TITLE
目前作品頁無「關鍵字」欄目可輸入

### ISSUE THREAD

**Issue by dream3cmp3** [fdjkgh580/issue_kypost#28]
目前作品頁無「關鍵字」欄目可輸入
這部分是否能讓客戶可以自己新增關鍵字的部分
比方說網站設定上設定關鍵字
然後作品案例新增關鍵字這樣？

**Comment by fdjkgh580** [comment]
@dream3cmp3 
後臺添加了欄位，如果沒有指定關鍵字，系統就預設套用網站的關鍵字喔
